name: Deploy to demo

on:
  repository_dispatch:
    types: [deploy-demo]

jobs:
  deploy-demo:
    # This workflow uses the staging image, since production utilize a different nginx.config
    name: Deploy latest staging image to demo environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/fdk-nginx-search
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-nginx-search:${{ github.event.client_payload.sha }}" -f ./helm/fdk-nginx-search/values/demo.yaml ./helm/fdk-nginx-search/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          project_id: digdir-fdk-dev
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-dev

      - name: Deploy to demo
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

#      - name: Notify slack
#        uses: 8398a7/action-slack@v3
#        with:
#          mention: 'channel'
#          if_mention: failure
#          status: ${{ job.status }}
#          author_name: 'Application: fdk-nginx-search | Environment: demo'
#          fields: commit,author,workflow
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always()
